export const podiumData = [
  {
    name: "Runners Up",
    amt: "Coming Soon...",
    webp: "prizes/webp/runnerup.webp",
    img: "prizes/runnerup.png",
    id: "r",
    cStyle: {
      paddingTop: "1.75rem",
      top: "-0.875rem",
      position: "relative",
    },
    desc: [
      "Rs.800 Coupon From GFG",
      "Wolfram Award letter",
      "Lifetime upgrade of Taskade",
      "Unlimited mock interviews from Interview Buddy",
      "Leading Learners Expansion Pack",
      "Swags and Stickers",
    ],
  },
  {
    name: "Winner Team",
    amt: "Coming Soon...",
    webp: "prizes/webp/winner.webp",
    img: "prizes/winner.png",
    id: "w",
    cStyle: {
      paddingTop: "3rem",
      top: "-1.5rem",
      position: "relative",
    },
    desc: [
      "Coupon From GFG",
      "Wolfram Award letter",
      "Lifetime upgrade of Taskade",
      "Unlimited mock interviews from Interview Buddy",
      "Leading Learners Expansion Pack",
      "Swags and Stickers",
    ],
  },
  {
    name: "2nd Runner Up",
    amt: "Coming Soon...",
    webp: "prizes/webp/3rd.webp",
    img: "prizes/3rd.png",
    id: "g",
    cStyle: {
      paddingTop: "0rem",
    },
    desc: [
      "Rs.500 Coupon From GFG",
      "Wolfram Award letter",
      "Lifetime upgrade of Taskade",
      "Unlimited mock interviews from Interview Buddy",
      "Leading Learners Expansion Pack",
      "Swags and Stickers",
    ],
  },
];
export const prizesData = [
  {
    name: "DOMAIN 1",
    amt: "Coming Soon...",
    webp: "prizes/webp/climate.webp",
    img: "prizes/climate.png",
    desc: [
      "Wolfram Award letter",
      "Coding Minutes Course for each Team Member",
      "Leading Learners Expansion packs",
      "Swags and Stickers",
    ],
  },
  {
    name: "Pandemic",
    amt: "Coming Soon...",
    webp: "prizes/webp/pandemic.webp",
    img: "prizes/pandemic.png",
    desc: [
      "Wolfram Award letter",
      "Coding Minutes Course for each Team Member",
      "Leading Learners Expansion packs",
      "Swags and Stickers",
    ],
  },
  {
    name: "Cyber Bullying",
    amt: "Coming Soon...",
    webp: "prizes/webp/cyber.webp",
    img: "prizes/cyber.png",
    desc: [
      "Wolfram Award letter",
      "Coding Minutes Course for each Team Member",
      "Leading Learners Expansion packs",
      "Swags and Stickers",
    ],
  },
  {
    name: "Natural Disaster",
    amt: "Coming Soon...",
    webp: "prizes/webp/disaster.webp",
    img: "prizes/disaster.png",
    desc: [
      "Wolfram Award letter",
      "Coding Minutes Course for each Team Member",
      "Leading Learners Expansion packs",
      "Swags and Stickers",
    ],
  },
  {
    name: "Hunger Eradication",
    amt: "Coming Soon...",
    webp: "prizes/webp/hunger.webp",
    img: "prizes/hunger.png",
    desc: [
      "Wolfram Award letter",
      "Coding Minutes Course for each Team Member",
      "Leading Learners Expansion packs",
      "Swags and Stickers",
    ],
  },
  {
    name: "Open Innovation",
    amt: "Worth 5000/- INR",
    webp: "prizes/webp/innovation.webp",
    img: "prizes/innovation.png",
    desc: [
      "Wolfram Award letter",
      "Coding Minutes Course for each Team Member",
      "Leading Learners Expansion packs",
      "Swags and Stickers",
    ],
  },
  {
    name: "Best Beginner hack",
    amt: "Worth 5000/- INR",
    webp: "prizes/webp/beginnerhack.webp",
    img: "prizes/beginnerhack.png",
    desc: [
      "Coding Minutes Course for each Team Member",
      "Egghead course for Web Development to each participant",
    ],
  },
  {
    name: "All Girls Team",
    amt: "Worth 5000/- INR",
    webp: "prizes/webp/girls.webp",
    img: "prizes/girls.png",
    desc: [
      "Wolfram Award letter",
      "Coding Minutes Course for each Team Member",
      "Leading Learners Expansion packs",
      "Swags and Stickers",
    ],
  },
];

export const allParticipants = {
  name: "All Participants",
  amt: "Cash Prize",
  webp: "prizes/webp/celebration.webp",
  img: "prizes/celebration.png",
  desc: [
    "Full access licenses of Interview Cake for Interview prep",
    "Rs.300 Coupons from GFG",
    "5-Year free upgrades from Taskade",
    "Access to WolframOne for all your participants for thirty days",
    "90-day extended trial promo code for Balsamiq Cloud",
    "Coupons for top brands from GrabOn",
    "Premium Tier service from Echo3D",
    "Hacker Plan from Repl.it",
    "Professional License Voiceflow",
    "Coupon Voucher from Interview Buddy",
  ],
};
