export const data = [
  {
    tierName: "Full Moon",
    data: [
      {
        sponsorName: "Devfolio",
        webp: "sponsors/fullmoon/webp/devfolio.webp",
        src: "sponsors/fullmoon/devfolio.png",
        url: "https://devfolio.co/",
        id: "gold_2",
      },
      // {
      //   sponsorName: "Echo 3D",
      //   webp: "sponsors/gold/webp/echo3d.webp",
      //   src: "sponsors/gold/echo3d.png",
      //   url: "https://www.echo3d.co/",
      //   id: "gold_3",
      // },
      {
        sponsorName: "PolyGon",
        webp: "sponsors/fullmoon/webp/polygon.webp",
        src: "sponsors/fullmoon/polygon.png",
        url: "https://polygon.technology/",
        id: "gold_6",
      },
    ],
    id: "1",
  },
  {
    tierName: "Gibbous",
    data: [
      // {
      //   sponsorName: "Egghead",
      //   webp: "sponsors/silver/webp/Egghead.webp",
      //   src: "sponsors/silver/Egghead.png",
      //   url: "https://egghead.io/",
      //   id: "silver_0",
      // },
      {
        sponsorName: "Replit",
        webp: "sponsors/gibbous/webp/Replit.webp",
        src: "sponsors/gibbous/Replit.png",
        url: "https://replit.com/",
        id: "gold_7",
      },
      // {
      //   sponsorName: "Koii",
      //   webp: "sponsors/silver/webp/koii.webp",
      //   src: "sponsors/silver/koii.png",
      //   url: "https://koii.network/",
      //   id: "silver_1",
      // },
      // {
      //   sponsorName: "Celo",
      //   webp: "sponsors/silver/webp/celo.webp",
      //   src: "sponsors/silver/celo.png",
      //   url: "https://celo.org/",
      //   id: "silver_2",
      // },
      {
        sponsorName: "Filecoin",
        webp: "sponsors/gibbous/webp/filecoin.webp",
        src: "sponsors/gibbous/filecoin.png",
        url: "https://filecoin.io/",
        id: "silver_3",
      },
      {
        sponsorName: "Solana",
        webp: "sponsors/gibbous/webp/solana.webp",
        src: "sponsors/gibbous/solana.png",
        url: "https://solana.com/",
        id: "silver_3",
      },
      // {
      //   sponsorName: "Tezos",
      //   webp: "sponsors/silver/webp/tezos.webp",
      //   src: "sponsors/silver/tezos.png",
      //   url: "https://tezos.com/",
      //   id: "silver_4",
      // },
      // {
      //   sponsorName: "Sketch",
      //   webp: "sponsors/silver/webp/sketch.webp",
      //   src: "sponsors/silver/sketch.",
      //   url: "https://www.sketch.com/",
      //   id: "silver_5",
      // },
      // {
      //   sponsorName: "Alan AI",
      //   webp: "sponsors/silver/webp/alan.webp",
      //   src: "sponsors/silver/alan.png",
      //   url: "https://bit.ly/3o8VFwm",
      //   id: "silver_7",
      // },
    ],
    id: "2",
  },
  // {
  //   tierName: "Crescent",
  //   data: [
  //     {
  //       sponsorName: "Give My Certificate",
  //       webp: "sponsors/bronze/webp/givemycertificate.webp",
  //       src: "sponsors/bronze/givemycertificate.png",
  //       url: "https://givemycertificate.com/",
  //       id: "bronze_2",
  //     },
  //     
  //     {
  //       sponsorName: "Coil",
  //       webp: "sponsors/bronze/webp/coil.webp",
  //       src: "sponsors/bronze/coil.png",
  //       url: "https://coil.com/",
  //       id: "bronze_4",
  //     },
  //   ],
  //   id: "3",
  // },
  {
    tierName: "Previous Sponsors",
    data: [
      {
        sponsorName: "GitHub",
        webp: "sponsors/previous/webp/Github.webp",
        src: "sponsors/previous/Github.png",
        url: "https://github.com/",
        id: "title_0",
      },
      {
        sponsorName: "GitLab",
        webp: "sponsors/previous/webp/gitlab.webp",
        src: "sponsors/previous/gitlab.png",
        url: "https://about.gitlab.com/",
        id: "title_1",
      },
      {
        sponsorName: "The @ Company",
        webp: "sponsors/previous/webp/atcomp.webp",
        src: "sponsors/previous/atcomp.png",
        url: "https://atsign.com/",
        id: "title_2",
      },
      {
        sponsorName: "Major League Hacking",
        webp: "sponsors/previous/webp/mlh.webp",
        src: "sponsors/previous/mlh.png",
        url: "https://mlh.io/",
        id: "title_3",
      },
      {
        sponsorName: "Devfolio",
        webp: "sponsors/fullmoon/webp/devfolio.webp",
        src: "sponsors/fullmoon/devfolio.png",
        url: "https://devfolio.co/",
        id: "gold_2",
      },
      {
        sponsorName: "GeeksForGeeks",
        webp: "sponsors/previous/webp/GFG.webp",
        src: "sponsors/previous/GFG.png",
        url: "https://www.geeksforgeeks.org/",
        id: "gold_4",
      },
      {
        sponsorName: "Interview Cake",
        webp: "sponsors/previous/webp/InterviewCake.webp",
        src: "sponsors/previous/InterviewCake.png",
        url: "https://www.interviewcake.com/",
        id: "gold_5",
      },
      {
        sponsorName: "Balsamiq",
        webp: "sponsors/previous/webp/balsamiq.webp",
        src: "sponsors/previous/balsamiq.png",
        url: "https://balsamiq.com/",
        id: "gold_0",
      },
      {
        sponsorName: "Replit",
        webp: "sponsors/gibbous/webp/Replit.webp",
        src: "sponsors/gibbous/Replit.png",
        url: "https://replit.com/",
        id: "gold_7",
      },
      {
        sponsorName: "Coding Minutes",
        webp: "sponsors/previous/webp/CodingMinutes.webp",
        src: "sponsors/previous/CodingMinutes.png",
        url: "https://www.codingminutes.com/",
        id: "gold_1",
      },
      {
        sponsorName: "StreamYard",
        webp: "sponsors/previous/webp/streamyard.webp",
        src: "sponsors/previous/streamyard.png",
        url: "https://streamyard.com/",
        id: "title_4",
      },
      {
        sponsorName: "Stickermule",
        webp: "sponsors/previous/webp/stickermule.webp",
        src: "sponsors/previous/stickermule.png",
        url: "http://hackp.ac/mlh-stickermule-hackathons",
        id: "silver_6",
      },
      {
        sponsorName: "Taskade",
        webp: "sponsors/previous/webp/Taskade.webp",
        src: "sponsors/previous/Taskade.png",
        url: "https://www.taskade.com/",
        id: "gold_8",
      },
      {
        sponsorName: "Voiceflow",
        webp: "sponsors/previous/webp/voiceflow.webp",
        src: "sponsors/previous/voiceflow.png",
        url: "https://www.voiceflow.com/",
        id: "gold_9",
      },
      {
        sponsorName: "Wolfram",
        webp: "sponsors/previous/webp/wolfram.webp",
        src: "sponsors/previous/wolfram.png",
        url: "https://www.wolfram.com/",
        id: "gold_10",
      },
      {
      sponsorName: "Interview Buddy",
              webp: "sponsors/previous/webp/interviewbuddy.webp",
              src: "sponsors/previous/interviewbuddy.png",
              url: "https://interviewbuddy.in/",
              id: "bronze_3",
      },
      {
        sponsorName: "Jdoodle",
        webp: "sponsors/previous/webp/Jdoodle.webp",
        src: "sponsors/previous/Jdoodle.png",
        url: "https://www.jdoodle.com/",
        id: "bronze_1",
      },
    ],
    id: "4",
  },
  // {
  //   tierName: "Title Sponsors",
  //   data: [
  //   ],
  //   id: "0",
  // },
];
