export const data = [
  {
    tierName: "Full Moon",
    data: [
      {
        sponsorName: "Devfolio",
        webp: "sponsors/fullmoon/webp/devfolio.webp",
        src: "sponsors/fullmoon/devfolio.png",
        url: "https://devfolio.co/",
        id: "gold_2",
      },
      // {
      //   sponsorName: "Echo 3D",
      //   webp: "sponsors/gold/webp/echo3d.webp",
      //   src: "sponsors/gold/echo3d.png",
      //   url: "https://www.echo3d.co/",
      //   id: "gold_3",
      // },
      {
        sponsorName: "PolyGon",
        webp: "sponsors/fullmoon/webp/polygon.webp",
        src: "sponsors/fullmoon/polygon.png",
        url: "https://polygon.technology/",
        id: "gold_6",
      },
      {
        sponsorName: "Quine",
        webp: "sponsors/fullmoon/webp/quine.webp",
        src: "sponsors/fullmoon/quine.png",
        url: "https://quine.sh/",
        id: "gold_5",
      },
      {
        sponsorName: "Showwcase",
        webp: "sponsors/fullmoon/webp/showwcase.webp",
        src: "sponsors/fullmoon/showwcase.png",
        url: "https://www.showwcase.com/",
        id: "gold_3",
      },
      {
        sponsorName: "5ire",
        webp: "sponsors/fullmoon/webp/5ire.webp",
        src: "sponsors/fullmoon/5ire.png",
        url: "https://www.5ire.org/",
        id: "gold_4",
      },
    ],
    id: "1",
  },
  {
    tierName: "Gibbous",
    data: [
      // {
      //   sponsorName: "Egghead",
      //   webp: "sponsors/silver/webp/Egghead.webp",
      //   src: "sponsors/silver/Egghead.png",
      //   url: "https://egghead.io/",
      //   id: "silver_0",
      // },
      {
        sponsorName: "Replit",
        webp: "sponsors/gibbous/webp/Replit.webp",
        src: "sponsors/gibbous/Replit.png",
        url: "https://replit.com/",
        id: "gibbous_3",
      },
      // {
      //   sponsorName: "Koii",
      //   webp: "sponsors/silver/webp/koii.webp",
      //   src: "sponsors/silver/koii.png",
      //   url: "https://koii.network/",
      //   id: "silver_1",
      // },
      // {
      //   sponsorName: "Celo",
      //   webp: "sponsors/silver/webp/celo.webp",
      //   src: "sponsors/silver/celo.png",
      //   url: "https://celo.org/",
      //   id: "silver_2",
      // },
      {
        sponsorName: "Filecoin",
        webp: "sponsors/gibbous/webp/filecoin.webp",
        src: "sponsors/gibbous/filecoin.png",
        url: "https://filecoin.io/",
        id: "gibbous_1",
      },
      {
        sponsorName: "Solana",
        webp: "sponsors/gibbous/webp/solana.webp",
        src: "sponsors/gibbous/solana.png",
        url: "https://solana.com/",
        id: "gibbous_2",
      },
      {
        sponsorName: "HoverRobotix",
        webp: "sponsors/gibbous/webp/robotix.webp",
        src: "sponsors/gibbous/robotix.png",
        url: "https://hoverrobotix.com/",
        id: "gibbous_4",
      },
      {
        sponsorName: "Jumbochain",
        webp: "sponsors/gibbous/webp/jumbochain.webp",
        src: "sponsors/gibbous/jumbochain.png",
        url: "https://www.jumbochain.org/",
        id: "gibbous_8",
      },
      {
        sponsorName: "XYZ Domains",
        webp: "sponsors/gibbous/webp/xyz.webp",
        src: "sponsors/gibbous/xyz.png",
        url: "https://gen.xyz/",
        id: "gibbous_9",
      },
      {
        sponsorName: "MentorX",
        webp: "sponsors/gibbous/webp/mentor.webp",
        src: "sponsors/gibbous/mentor.png",
        url: "https://thementorx.com/",
        id: "gibbous_5",
      },
      {
        sponsorName: "RevUp",
        webp: "sponsors/gibbous/webp/revup.webp",
        src: "sponsors/gibbous/revup.png",
        url: "http://nancyjuneja.com/rev-up-life-skill/",
        id: "gibbous_6",
      },
      {
        sponsorName: "Interview Cake",
        webp: "sponsors/gibbous/webp/InterviewCake.webp",
        src: "sponsors/gibbous/InterviewCake.png",
        url: "https://www.interviewcake.com/",
        id: "gibbous_7",
      },
      // {
      //   sponsorName: "Tezos",
      //   webp: "sponsors/silver/webp/tezos.webp",
      //   src: "sponsors/silver/tezos.png",
      //   url: "https://tezos.com/",
      //   id: "silver_4",
      // },
      // {
      //   sponsorName: "Sketch",
      //   webp: "sponsors/silver/webp/sketch.webp",
      //   src: "sponsors/silver/sketch.",
      //   url: "https://www.sketch.com/",
      //   id: "silver_5",
      // },
      // {
      //   sponsorName: "Alan AI",
      //   webp: "sponsors/silver/webp/alan.webp",
      //   src: "sponsors/silver/alan.png",
      //   url: "https://bit.ly/3o8VFwm",
      //   id: "silver_7",
      // },
    ],
    id: "2",
  },
  {
    tierName: "Crescent",
    data: [
      {
        sponsorName: "Taskade",
        webp: "sponsors/crescent/webp/Taskade.webp",
        src: "sponsors/crescent/Taskade.png",
        url: "https://www.taskade.com/",
        id: "crescent_8",
      },
      {
        sponsorName: "StickerYou",
        webp: "sponsors/crescent/webp/sticker.webp",
        src: "sponsors/crescent/sticker.png",
        url: "https://www.stickeryou.com/",
        id: "crescent_2",
      },
      {
        sponsorName: "Julia",
        webp: "sponsors/crescent/webp/julia.webp",
        src: "sponsors/crescent/julia.png",
        url: "https://julialang.org/",
        id: "crescent_1",
      },

      {
        sponsorName: "Voiceflow",
        webp: "sponsors/crescent/webp/voiceflow.webp",
        src: "sponsors/crescent/voiceflow.png",
        url: "https://www.voiceflow.com/",
        id: "crescent_9",
      },
      {
        sponsorName: "Wolfram",
        webp: "sponsors/crescent/webp/wolfram.webp",
        src: "sponsors/crescent/wolfram.png",
        url: "https://www.wolfram.com/",
        id: "crescent_10",
      },

      {
        sponsorName: "Balsamiq",
        webp: "sponsors/crescent/webp/balsamiq.webp",
        src: "sponsors/crescent/balsamiq.png",
        url: "https://balsamiq.com/",
        id: "crescent_0",
      },
    ],
    id: "3",
  },
  // {
  //   tierName: "Previous Sponsors",
  //   data: [

  //     {
  //       sponsorName: "GitLab",
  //       webp: "sponsors/previous/webp/gitlab.webp",
  //       src: "sponsors/previous/gitlab.png",
  //       url: "https://about.gitlab.com/",
  //       id: "title_1",
  //     },
  //     {
  //       sponsorName: "The @ Company",
  //       webp: "sponsors/previous/webp/atcomp.webp",
  //       src: "sponsors/previous/atcomp.png",
  //       url: "https://atsign.com/",
  //       id: "title_2",
  //     },
  //     {
  //       sponsorName: "GeeksForGeeks",
  //       webp: "sponsors/previous/webp/GFG.webp",
  //       src: "sponsors/previous/GFG.png",
  //       url: "https://www.geeksforgeeks.org/",
  //       id: "gold_4",
  //     },
  //     {
  //       sponsorName: "Coding Minutes",
  //       webp: "sponsors/previous/webp/CodingMinutes.webp",
  //       src: "sponsors/previous/CodingMinutes.png",
  //       url: "https://www.codingminutes.com/",
  //       id: "gold_1",
  //     },
  //     {
  //       sponsorName: "StreamYard",
  //       webp: "sponsors/previous/webp/streamyard.webp",
  //       src: "sponsors/previous/streamyard.png",
  //       url: "https://streamyard.com/",
  //       id: "title_4",
  //     },
  //     {
  //       sponsorName: "Stickermule",
  //       webp: "sponsors/previous/webp/stickermule.webp",
  //       src: "sponsors/previous/stickermule.png",
  //       url: "http://hackp.ac/mlh-stickermule-hackathons",
  //       id: "silver_6",
  //     },
  //     {
  //     sponsorName: "Interview Buddy",
  //     webp: "sponsors/previous/webp/interviewbuddy.webp",
  //     src: "sponsors/previous/interviewbuddy.png",
  //     url: "https://interviewbuddy.in/",
  //     id: "bronze_3",
  //     },
  //     {
  //       sponsorName: "Jdoodle",
  //       webp: "sponsors/previous/webp/Jdoodle.webp",
  //       src: "sponsors/previous/Jdoodle.png",
  //       url: "https://www.jdoodle.com/",
  //       id: "bronze_1",
  //     },
  //   ],
  //   id: "4",
  // },
  {
    tierName: "Title Sponsors",
    data: [
      // {
      //   sponsorName: "Major League Hacking",
      //   webp: "sponsors/fullmoon/webp/mlh.webp",
      //   src: "sponsors/fullmoon/mlh.png",
      //   url: "https://mlh.io/",
      //   id: "title_0",
      // },
      {
        sponsorName: "GitHub",
        webp: "sponsors/fullmoon/webp/Github.webp",
        src: "sponsors/fullmoon/Github.png",
        url: "https://github.com/",
        id: "title_1",
      },
    ],
    id: "0",
  },
];
